---
- name: install iis
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait 300 seconds for server to come up
      wait_for_connection:
        timeout: 300
    - name: Gather facts for first time
      setup:
    - name: Install IIS (Web-Server only)
      win_feature: >
          name=Web-Server
          include_management_tools=yes
          include_sub_features=yes
          state=present
      register: result
    - name: reboot server
      win_reboot:
        msg: "Installing AD. Rebooting..."
        pre_reboot_delay: 20
      when: ad.changed
