---
- hosts: localhost
  gather_facts: no
  become: false
  tasks:
    - name: create linux_httpd group
      amazon.aws.ec2_group:
        name: linux_httpd
        description: sg for httpd
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: "-1"
            from_port: 0
            to_port: 0
            cidr_ip: 0.0.0.0/0
      environment: 
        AWS_REGION: "{{ AWS_REGION }}"  
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        key_name: mays_keypair
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        security_group: linux_httpd
        instance_type: t2.micro
        image_id: ami-03d64741867e7bb94
        wait: yes
        wait_timeout: 500
        tags:
           Name: RHEL-HTTPD
           owner: cmays
           AF_DEMO_ROLE: httpd
           DemoID: cmays
        network:
          assign_public_ip: yes
      environment: 
        AWS_REGION: "{{ AWS_REGION }}"
    - name: Pause for 30 seconds to let EC2 come up
      ansible.builtin.pause:
        seconds: 30
