---
- hosts: localhost
  gather_facts: no
  become: false
  tasks:
    - name: delete key pair using provided key_material
      amazon.aws.ec2_key:
        name: mays_keypair
        state: absent
      environment: 
        AWS_REGION: "{{ AWS_REGION }}"
    - name: delete ec2 instance
      amazon.aws.ec2_instance:
        filters:
          tag:Name: RHEL-HTTPD
        state: absent
      environment: 
        AWS_REGION: "{{ AWS_REGION }}"
    - name: delete linux_httpd group
      amazon.aws.ec2_group:
        name: linux_httpd
        state: absent
      environment: 
        AWS_REGION: "{{ AWS_REGION }}"
