---
- hosts: localhost
  gather_facts: no
  become: false
  tasks:
    - name: create key pair using provided key_material
      amazon.aws.ec2_key:
        name: mays_keypair
        key_material: "{{ key_material }}"
        force: false
      environment: 
        AWS_REGION: "{{ AWS_REGION }}"
