---
- hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: Get Terraform from github
    ansible.builtin.git:
      repo: https://github.com/cmays20/terraform-demo
      dest: "{{ terraform_dir }}"
  - name: connect to terraform and execute plan
    terraform:
      project_path: "{{ terraform_dir }}/linux"
      force_init: true
      variables:
        public_key: "{{ public_key }}"
